version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8081:8081

  notification-service:
    image: notificationservice
    build: notification-service/
    container_name: notificationservice-container
    network_mode: host
    hostname: localhost
    ports:
      - 8404:8080
    healthcheck:
      test: "exit 0"